# Generated by Django 4.1.7 on 2023-03-04 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_Profile',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='item_model',
            name='item_Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
