# Generated by Django 4.1.7 on 2023-03-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_user_profile_customer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item_Model',
            new_name='itemmodel',
        ),
        migrations.RenameModel(
            old_name='order_Item',
            new_name='orderitem',
        ),
    ]
