# Generated by Django 4.1.7 on 2023-03-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_item_model_itemmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='itemmodel',
            new_name='Product',
        ),
    ]
