# Generated by Django 4.1.7 on 2023-03-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_itemmodel_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='item_Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='item_Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='item_Price',
            new_name='price',
        ),
    ]
