# Generated by Django 4.1.7 on 2023-03-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_rename_item_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='prepared',
            field=models.BooleanField(default=False),
        ),
    ]
