# Generated by Django 4.1.7 on 2023-03-04 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item_Model',
            fields=[
                ('item_Name', models.CharField(max_length=250)),
                ('item_Image', models.ImageField(upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
