# Generated by Django 4.1.7 on 2023-03-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_model',
            name='item_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_model',
            name='item_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
