# Generated by Django 4.1.7 on 2023-03-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_item_model_item_price_alter_item_model_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_model',
            name='item_Desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
